#!/bin/sh
API=https://api.github.com/repos/syncthing/syncthing-inotify/releases/latest
docker build \
    --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --build-arg VCS_REF=`git rev-parse --short HEAD` \
    --build-arg VERSION=`curl -s $API | jq -r '.tag_name'` \
    -t $IMAGE_NAME .
