#!/bin/sh

BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
VCS_REF=`git rev-parse --short HEAD`
VERSION=`git ls-remote --tags https://github.com/syncthing/syncthing-inotify | grep -v - | grep -v { | awk '{print $2}' | awk -F"/" '{print $3}' | tail -n 1`

docker build \
    --build-arg BUILD_DATE=$BUILD_DATE \
    --build-arg VCS_REF=$VCS_REF \
    --build-arg VERSION=$VERSION \
    -t $IMAGE_NAME .
