#!/bin/sh

BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
VCS_REF=`git rev-parse --short HEAD`
VERSION=`git ls-remote --tags https://github.com/syncthing/syncthing-inotify \
    | grep -v - | grep -v { | awk '{print $2}' \
    | awk -F"/" '{print $3}' | tail -n 1 | sed 's/v//g'`

echo $BUILD_DATE
echo $VCS_REF
echo $VERSION

docker build \
    --build-arg BUILD_DATE=$BUILD_DATE \
    --build-arg VCS_REF=$VCS_REF \
    --build-arg VERSION=$VERSION \
    -t $IMAGE_NAME .

docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION
docker push $DOCKER_REPO:$VERSION
